from marshmallow import Schema, fields, validate

class PersonCreateSchema(Schema):
    first_name = fields.String(required=True, validate=validate.Length(min=1, max=50))
    middle_name = fields.String(allow_none=True)
    last_name = fields.String(required=True, validate=validate.Length(min=1, max=50))
    gender = fields.String(required=True, validate=validate.OneOf(['male', 'female', 'other']))
    date_of_birth = fields.String(allow_none=True)
    date_of_death = fields.String(allow_none=True)
    birthplace = fields.String(allow_none=True)
    occupation = fields.String(allow_none=True)
    biography = fields.String(allow_none=True)
    photo_url = fields.String(allow_none=True)
    current_lat = fields.Float(allow_none=True)
    current_lng = fields.Float(allow_none=True)
    current_location_name = fields.String(allow_none=True)
    status_message = fields.String(allow_none=True)

class PersonUpdateSchema(Schema):
    first_name = fields.String(validate=validate.Length(min=1, max=50))
    middle_name = fields.String(allow_none=True)
    last_name = fields.String(validate=validate.Length(min=1, max=50))
    gender = fields.String(validate=validate.OneOf(['male', 'female', 'other']))
    date_of_birth = fields.String(allow_none=True)
    date_of_death = fields.String(allow_none=True)
    birthplace = fields.String(allow_none=True)
    occupation = fields.String(allow_none=True)
    biography = fields.String(allow_none=True)
    photo_url = fields.String(allow_none=True)
    current_lat = fields.Float(allow_none=True)
    current_lng = fields.Float(allow_none=True)
    current_location_name = fields.String(allow_none=True)
    status_message = fields.String(allow_none=True)

class LocationUpdateSchema(Schema):
    latitude = fields.Float(required=True)
    longitude = fields.Float(required=True)
    location_name = fields.String(allow_none=True)
    status_message = fields.String(allow_none=True)

class PersonResponseSchema(Schema):
    id = fields.Int()
    family_id = fields.Int()
    first_name = fields.Str()
    middle_name = fields.Str(allow_none=True)
    last_name = fields.Str()
    gender = fields.Str()
    date_of_birth = fields.Str(allow_none=True)
    date_of_death = fields.Str(allow_none=True)
    birthplace = fields.Str(allow_none=True)
    occupation = fields.Str(allow_none=True)
    biography = fields.Str(allow_none=True)
    photo_url = fields.Str(allow_none=True)
    current_lat = fields.Float(allow_none=True)
    current_lng = fields.Float(allow_none=True)
    current_location_name = fields.Str(allow_none=True)
    status_message = fields.Str(allow_none=True)
    last_location_update = fields.Str(allow_none=True)
    created_at = fields.Str()
    updated_at = fields.Str()
